language: python
sudo: false
cache: pip
python: 3.5

env:
  - TOXENV=static
  - TOXENV=metrics
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

before_install:
  - pip install codecov

install: pip install tox
script: tox

after_success:
  - codecov

notifications:
  email:
    - nineseconds@yandex.ru
